apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: rancher
    repo: https://releases.rancher.com/server-charts/latest
    version: 2.8.2
    releaseName: rancher
    namespace: rancher
    valuesFile: values.yaml
