apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      version: 6.56.2
  interval: 5m
  values:
    adminPassword: changeme
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
        - disableDeletion: false
          folder: ''
          name: default
          options:
            path: /var/lib/grafana/dashboards/default
          orgId: 1
          type: file
    dashboards:
      default:
        argocd:
          datasource: Loki
          gnetId: 14584
          revision: 1
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        - access: proxy
          isDefault: true
          name: Loki
          type: loki
          url: http://loki.monitoring.svc.cluster.local:3100
    envFromSecrets:
    - name: grafana-okta-oauth
    grafana:
      auth:
        disable_login_form: true
        disable_signout_menu: false
      auth.generic_oauth:
        allow_sign_up: true
        api_url: https://emodo.okta.com/oauth2/default/v1/userinfo
        auth_url: https://emodo.okta.com/oauth2/default/v1/authorize
        client_id: ${GF_AUTH_GENERIC_OAUTH_CLIENT_ID}
        client_secret: ${GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET}
        enabled: true
        name: Okta
        role_attribute_path: contains(groups[*], 'grafana-admin') && 'Admin' || 'Viewer'
        scopes: openid profile email groups
        token_url: https://emodo.okta.com/oauth2/default/v1/token
    persistence:
      enabled: true
      size: 10Gi
