apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - crds/cert-manager.crds.yaml

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.17.2
    releaseName: cert-manager
    namespace: cert-manager
    valuesFile: values.yaml
