apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
  - namespace.yaml
  - cert-manager.crds.yaml

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.17.2
    releaseName: cert-manager
    namespace: cert-manager
    valuesFile: values.yaml  # ✅ This must exist in same directory

# 🚫 DO NOT add: type: helm  ← this causes "unknown field" in v4.x
