installCRDs: false  # Managed via separate YAML

replicaCount: 2  # HA setup

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

nodeSelector:
  kubernetes.io/os: linux

tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  - operator: "Exists"

webhook:
  timeoutSeconds: 10  # safer under load

podDisruptionBudget:
  enabled: true
  minAvailable: 1

prometheus:
  enabled: true
  servicemonitor:
    enabled: true  # ✅ turn on if using Prometheus Operator
    interval: 30s
    scrapeTimeout: 10s

ingressShim:
  defaultIssuerKind: ""   # leave blank unless all ingresses share same issuer
  defaultIssuerName: ""

extraArgs:
  - --enable-certificate-owner-ref=true
  - --cluster-resource-namespace=cert-manager
