installCRDs: true  # Recommended for Helm-based installations

replicaCount: 2  # High availability

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

nodeSelector:
  kubernetes.io/os: linux

tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  - operator: "Exists"

webhook:
  timeoutSeconds: 5

podDisruptionBudget:
  enabled: true
  minAvailable: 1

prometheus:
  enabled: true
  servicemonitor:
    enabled: true
    interval: 30s
    scrapeTimeout: 10s

ingressShim:
  defaultIssuerKind: ""
  defaultIssuerName: ""

extraArgs:
  - --enable-certificate-owner-ref=true
  - --cluster-resource-namespace=cert-manager
