apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  # Add other Longhorn resources here as needed

# Common labels to apply to all resources
commonLabels:
  app: longhorn
  app.kubernetes.io/name: longhorn
  app.kubernetes.io/instance: longhorn
  app.kubernetes.io/component: storage
  app.kubernetes.io/part-of: longhorn

# Name prefix for all resources
namePrefix: longhorn-

# Name suffix for all resources (optional)
# nameSuffix: -suffix

# Namespace to deploy all resources
namespace: longhorn-system
