apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.metrics.k8s.io
spec:
  service:
    name: metrics-server
    namespace: metrics-test     # ✅ fix here
  group: metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true   # Optional for self-signed certs
  groupPriorityMinimum: 100
  versionPriority: 100

