apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base Grafana configuration but exclude the PVC
resources:
  - ../../../../base/grafana

# Remove the PVC resource
patches:
  - target:
      kind: PersistentVolumeClaim
      name: grafana-storage
    patch: |-
      $patch: delete

# Patch the Deployment to use emptyDir and update security context
  - path: json-patch.yaml
    target:
      kind: Deployment
      name: grafana

# Remove the PVC resource from the base resources
resources:
  - ../../../../base/grafana/namespace.yaml
  - ../../../../base/grafana/rbac.yaml
  - ../../../../base/grafana/service.yaml
  - ../../../../base/grafana/serviceaccount.yaml
  - ../../../../base/grafana/deployment.yaml
  - ../../../../base/grafana/hpa.yaml
  - ../../../../base/grafana/configmap.yaml
  # Intentionally excluding the pvc.yaml file

# Common labels for all resources
commonLabels:
  app.kubernetes.io/environment: prod
  app.kubernetes.io/cluster: dc11a

# Namespace
namespace: monitoring

# Images
images:
  - name: grafana/grafana
    newName: grafana/grafana
    newTag: 10.4.2

# Common annotations
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  argocd.argoproj.io/sync-wave: "-1"

# Patch the HPA to adjust scaling for dc11a
patches:
  - target:
      kind: HorizontalPodAutoscaler
      name: grafana
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 3
