apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Disable load restrictions to allow referencing files outside the overlay
configurations:
  - kustomizeconfig.yaml

# Reference the base Grafana configuration from Helm chart
resources:
  - ../../../../base/grafana/charts/grafana-7.2.0/grafana/templates/namespace.yaml
  - ../../../../base/grafana/charts/grafana-7.2.0/grafana/templates/serviceaccount.yaml
  - ../../../../base/grafana/charts/grafana-7.2.0/grafana/templates/configmap.yaml
  - ../../../../base/grafana/charts/grafana-7.2.0/grafana/templates/service.yaml
  - ../../../../base/grafana/charts/grafana-7.2.0/grafana/templates/deployment.yaml
  - ../../../../base/grafana/charts/grafana-7.2.0/grafana/templates/hpa.yaml

# Remove the PVC resource
patches:
  - target:
      kind: PersistentVolumeClaim
      name: grafana-storage
    patch: |-
      $patch: delete

# Patch the Deployment to use emptyDir and update security context
  - path: json-patch.yaml
    target:
      kind: Deployment
      name: grafana

# Patch the HPA to adjust scaling for dc11a
  - target:
      kind: HorizontalPodAutoscaler
      name: grafana
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 3

# Common labels for all resources
commonLabels:
  app.kubernetes.io/environment: prod
  app.kubernetes.io/cluster: dc11a

# Namespace
namespace: monitoring

# Images
images:
  - name: grafana/grafana
    newName: grafana/grafana
    newTag: 10.4.2

# Common annotations
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  argocd.argoproj.io/sync-wave: "-1"

# Patch the HPA to adjust scaling for dc11a
patches:
  - target:
      kind: HorizontalPodAutoscaler
      name: grafana
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 3
