apiVersion: v1
data:
  oidc.config: 'name: Okta

    issuer: https://emodo.okta.com/oauth2/default

    clientID: okta-client-id

    clientSecret: okta-client-secret

    requestedScopes: ["openid", "profile", "email"]

    '
  url: https://argocd.emodo.com
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
