replicas: 2

hostNetwork: true
dnsPolicy: ClusterFirstWithHostNet

args:
  - --cert-dir=/tmp
  - --secure-port=4443
  - --kubelet-insecure-tls
  - --kubelet-use-node-status-port
  - --kubelet-preferred-address-types=InternalIP,Hostname
  - --metric-resolution=15s

service:
  port: 443
  targetPort: 4443
  type: ClusterIP

apiService:
  insecureSkipTLSVerify: true
  port: 443

resources:
  requests:
    cpu: 100m
    memory: 200Mi
  limits:
    cpu: 250m
    memory: 400Mi

livenessProbe:
  enabled: true
  httpGet:
    path: /livez
    port: 4443
    scheme: HTTPS
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3

readinessProbe:
  enabled: true
  httpGet:
    path: /readyz
    port: 4443
    scheme: HTTPS
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s
    scrapeTimeout: 10s
    additionalLabels:
      release: prometheus

nodeSelector:
  kubernetes.io/os: linux

tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"
  - operator: "Exists"

priorityClassName: system