replicas: 2

hostNetwork: true
dnsPolicy: ClusterFirstWithHostNet

args:
  - --cert-dir=/tmp
  - --secure-port=4443
  - --kubelet-insecure-tls
  - --kubelet-use-node-status-port
  - --kubelet-preferred-address-types=InternalIP,Hostname
  - --metric-resolution=15s

service:
  port: 443
  targetPort: 4443

resources:
  requests:
    cpu: 100m
    memory: 200Mi
  limits:
    cpu: 250m
    memory: 400Mi
