replicaCount: 2

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60

isClusterService: true

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists

tolerations:
  - key: "CriticalAddonsOnly"
    operator: "Exists"
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"

servers:
  - zones:
      - "."
    port: 53
    plugins:
      - name: errors
      - name: health
      - name: ready
      - name: kubernetes
        parameters: "cluster.local in-addr.arpa ip6.arpa"
        configBlock: |
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
      - name: forward
        parameters: ". /etc/resolv.conf"
        configBlock: |
          max_concurrent 1000
      - name: cache
        parameters: 30
      - name: loop
      - name: reload
      - name: loadbalance