apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-self
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
      values:
        cluster: "{{name}}" # Uses cluster name (dc11a or dc11b)
  template:
    metadata:
      name: argocd-self-{{name}}
    spec:
      project: default
      source:
        repoURL: https://github.com/vietcgi/infra.git
        targetRevision: HEAD
        path: apps/system/overlays/prod/shared/argocd
        kustomize:
          enableHelm: true  # Enable Helm support for Kustomize
          buildOptions: ["--enable-helm"]  # Explicitly enable Helm for Kustomize build
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      ignoreDifferences:
        - group: ""
          kind: Secret
          name: argocd-secret
