apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -dc11a

resources:
- ../../../../base/longhorn

helmCharts:
- name: longhorn
  releaseName: longhorn
  repo: https://charts.longhorn.io
  version: 1.6.0
  namespace: longhorn-system
  valuesFile: ../../../../base/longhorn/values.yaml
  valuesMerge: override
  valuesInline:
    controller:
      replicas: 1
  includeCRDs: true

# Enable Helm support for Kustomize
buildOptions:
  - enable-helm
