apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Name suffix for all resources
nameSuffix: -dc11a

# Include the base Longhorn manifests
resources:
  - ../../../../base/longhorn
  - webhook-patch.yaml

# Common labels to apply to all resources
commonLabels:
  app.kubernetes.io/instance: longhorn-dc11a
  app.kubernetes.io/part-of: longhorn
  app.kubernetes.io/managed-by: kustomize

# Namespace to deploy all resources
namespace: longhorn-system

# Patch the webhook configurations to use the correct service name
patches:
  - target:
      kind: ValidatingWebhookConfiguration
      name: longhorn-admission-webhook
    patch: |-
      - op: replace
        path: /webhooks/0/clientConfig/service/name
        value: longhorn-longhorn-admission-webhook-dc11a
  - target:
      kind: MutatingWebhookConfiguration
      name: longhorn-conversion-webhook
    patch: |-
      - op: replace
        path: /webhooks/0/clientConfig/service/name
        value: longhorn-longhorn-conversion-webhook-dc11a
