apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-helm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana-helm
    app.kubernetes.io/part-of: kube-system
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 7.3.6
    chart: grafana
    helm:
      releaseName: grafana
      values: |
        # Set admin credentials
        adminUser: admin
        adminPassword: grafana123

        # Disable persistence
        persistence:
          enabled: false

        # Service configuration
        service:
          type: ClusterIP

        # Disable ingress
        ingress:
          enabled: false

        # Bypass secret validation
        assertNoLeakedSecrets: false

        # Configure security context to run as root to avoid permission issues
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          fsGroup: 0
          runAsNonRoot: false

        # Configure container security context
        containerSecurityContext:
          allowPrivilegeEscalation: true
          readOnlyRootFilesystem: false
          runAsUser: 0
          runAsGroup: 0
          runAsNonRoot: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
