resources:
  - namespace.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: sealed-secrets
    repo: https://bitnami-labs.github.io/sealed-secrets
    version: 2.29.0
    releaseName: sealed-secrets
    namespace: sealed-secrets
    valuesFile: values.yaml
