resources:
  - networkpolicy.yaml
  - namespace.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 8.0.10
    releaseName: argocd
    namespace: argocd
    valuesFile: values.yaml
