configs:
  cm:
    kustomize.buildOptions: --enable-helm

  rbac:
    policy.default: role:readonly
    
  secret:
    argocdServerAdminPassword: $2b$12$oKokPM7N8GEWQALP0J.Hhe6nUdxIo4nItFuGtqlUr3jpld5OkWQn6

networkPolicy:
  create: true
  allowInternal: true

applicationSet:
  enabled: true

installCRDs: true

server:
  service:
    type: ClusterIP

controller:
  replicas: 1

repoServer:
  replicas: 1

dex:
  enabled: true

redis:
  enabled: true

notifications:
  enabled: true
