apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - https://github.com/prometheus-operator/prometheus-operator/releases/latest/download/bundle.yaml

