apiVersion: v1
kind: ConfigMap
metadata:
  name: nodelocaldns
  namespace: kube-system
  labels:
    k8s-app: node-local-dns
data:
  Corefile: |
    .:53 {
        errors
        cache {
            success 9984 30
            denial 9984 5
        }
        reload
        loop
        bind 169.254.20.10
        forward . /etc/resolv.conf
        prometheus 127.0.0.1:9253
        log
    }

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nodelocaldns
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: node-local-dns
  template:
    metadata:
      labels:
        k8s-app: node-local-dns
    spec:
      serviceAccountName: nodelocaldns
      priorityClassName: system-cluster-critical
      hostNetwork: true
      dnsPolicy: Default
      containers:
        - name: node-cache
          image: registry.k8s.io/dns/nodelocaldns:1.26.0
          args:
            - -localip
            - 169.254.20.10
            - -conf
            - /etc/coredns/Corefile
            - -upstreamsvc
            - kube-dns
          ports:
            - containerPort: 53
              protocol: UDP
            - containerPort: 53
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "25m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/coredns
            - name: xtables-lock
              mountPath: /run/xtables.lock
      tolerations:
        - operator: Exists
      volumes:
        - name: config-volume
          configMap:
            name: nodelocaldns
        - name: xtables-lock
          hostPath:
            path: /run/xtables.lock
            type: FileOrCreate
