apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns
  namespace: kube-system
spec:
  replicas: 1
  template:
    spec:
      tolerations:
        - operator: "Exists"
      containers:
        - name: coredns
          resources:
            requests:
              cpu: 30m
              memory: 70Mi
            limits:
              memory: 170Mi
