apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: system-apps-dev
  namespace: argocd
  labels:
    environment: dev
    type: system
spec:
  generators:
    - list:
        elements:
          - name: cert-manager
            namespace: cert-manager
            syncWave: "-1"
          - name: cilium
            namespace: kube-system
          - name: coredns
            namespace: kube-system
          - name: prometheus
            namespace: monitoring
          - name: argocd
            namespace: argocd
          - name: loki
            namespace: monitoring
          - name: grafana
            namespace: monitoring
          - name: nginx-ingress
            namespace: ingress-nginx
          - name: rancher
            namespace: cattle-system
          - name: alertmanager
            namespace: monitoring
          - name: sealed-secrets
            namespace: kube-system
            syncWave: "-2"
          - name: metrics-server
            namespace: kube-system
          - name: neuvector
            namespace: neuvector
          - name: longhorn
            namespace: longhorn-system
  template:
    metadata:
      name: '{{name}}-dev'
      labels:
        app: '{{name}}'
        environment: dev
      annotations:
        argocd.argoproj.io/sync-wave: '{{syncWave}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/vietcgi/infractl.git
        targetRevision: dev
        path: apps/system/overlays/dev/{{name}}
        kustomize:
          buildOptions: --enable-helm
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - Validate=true
        automated:
          prune: true
          selfHeal: true
