apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - serviceaccount.yaml
  - clusterrolebinding.yaml
  - rolebinding.yaml
  - clusterrole.yaml
  - service.yaml
  - apiservice.yaml