apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metrics-server
  namespace: metrics-server
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      k8s-app: metrics-server
  namespaceSelector:
    matchNames:
      - metrics-server
  endpoints:
    - port: https
      interval: 30s
      scheme: https
      path: /metrics
      tlsConfig:
        insecureSkipVerify: true
