apiVersion: v1
kind: Service
metadata:
  name: metrics-server
  namespace: metrics-server
spec:
  selector:
    k8s-app: metrics-server
  ports:
    - port: 443
      targetPort: 4443
      protocol: TCP
      name: https

