apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: system-apps
  namespace: argocd
spec:
  generators:
  - git:
      directories:
      - path: system/*
      - path: projects/*
      - path: system/argocd-notifications
      repoURL: https://github.com/your-org/apps
      revision: HEAD
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      destination:
        namespace: '{{path.basename}}'
        server: https://kubernetes.default.svc
      project: default
      source:
        path: '{{path}}'
        repoURL: https://github.com/your-org/apps
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
