apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../base/metrics-server
  - hpa.yaml

patches:
  - path: patch-resources.yaml
    target:
      kind: Deployment
      name: metrics-server