apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-repo-creds
  namespace: argocd
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
spec:
  encryptedData:
    password: AgC3EXAMPLEENCRYPTEDDATAo4Uud5==  # Replace with real encryption
  template:
    metadata:
      name: argocd-repo-creds
      namespace: argocd
    type: Opaque
