{{- if and (eq .Values.platform "rke2") .Values.sealedSecrets.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sealed-secrets-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sealed-secrets-controller
  template:
    metadata:
      labels:
        name: sealed-secrets-controller
    spec:
      containers:
        - name: sealed-secrets-controller
          image: quay.io/bitnami/sealed-secrets-controller:v0.19.2
{{- end }}
