apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Disable load restrictions to allow referencing files outside the overlay
configurations:
  - kustomizeconfig.yaml

resources:
  - grafana
  - grafana-simple/
  - argocd/
  - monitoring/
  - metrics-server/
  - longhorn/
  - coredns/
  - sealed-secrets/
  - rancher/
  - prometheus-operator-crds/
  - prometheus/
  - nodelocaldns/
  - nginx-ingress/
  - neuvector/
  - cilium/
  - cert-manager-crds/
  - alertmanager/
  - loki/
  - cert-manager/ 