apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: system-apps-prod
  namespace: argocd
  labels:
    environment: prod
    type: system
spec:
  generators:
    - list:
        elements:
          - name: cert-manager-crds
            namespace: cert-manager
            syncWave: "-4"
            type: raw
          - name: prometheus-operator-crds
            namespace: monitoring
            syncWave: "-3"
            type: raw
          - name: sealed-secrets
            chart: sealed-secrets
            version: 2.15.3
            repoURL: https://bitnami-labs.github.io/sealed-secrets
            namespace: kube-system
            syncWave: "-2"
            type: helm
          - name: cert-manager
            chart: cert-manager
            version: 1.13.2
            repoURL: https://charts.jetstack.io
            namespace: cert-manager
            syncWave: "-1"
            type: helm
          - name: cilium
            chart: cilium
            version: 1.17.4
            repoURL: https://helm.cilium.io
            namespace: kube-system
            type: helm
          - name: coredns
            namespace: kube-system
            syncWave: "-2"
            type: raw
          - name: prometheus
            chart: kube-prometheus-stack
            version: 56.6.2
            repoURL: https://prometheus-community.github.io/helm-charts
            namespace: monitoring
            type: helm
          - name: argocd
            chart: argo-cd
            version: 8.0.10
            repoURL: https://argoproj.github.io/argo-helm
            namespace: argocd
            type: helm
          - name: loki
            chart: loki
            version: 5.44.0
            repoURL: https://grafana.github.io/helm-charts
            namespace: monitoring
            type: helm
          - name: grafana
            chart: grafana
            version: 7.3.10
            repoURL: https://grafana.github.io/helm-charts
            namespace: monitoring
            type: helm
          - name: nginx-ingress
            chart: ingress-nginx
            version: 4.9.0
            repoURL: https://kubernetes.github.io/ingress-nginx
            namespace: ingress-nginx
            type: helm
          - name: rancher
            chart: rancher
            version: 2.8.0
            repoURL: https://releases.rancher.com/server-charts/latest
            namespace: cattle-system
            type: helm
          - name: alertmanager
            chart: alertmanager
            version: 1.7.0
            repoURL: https://prometheus-community.github.io/helm-charts
            namespace: monitoring
            type: helm
          - name: metrics-server
            namespace: kube-system
            syncWave: "-1"
            type: raw
          - name: neuvector
            chart: core
            version: 2.6.6
            repoURL: https://neuvector.github.io/neuvector-helm
            namespace: neuvector
            type: helm
          - name: longhorn
            chart: longhorn
            version: 1.5.3
            repoURL: https://charts.longhorn.io
            namespace: longhorn-system
            type: helm
          - name: nodelocaldns
            namespace: kube-system
            syncWave: "-1"
            type: raw
  template:
    metadata:
      name: '{{name}}-prod'
      labels:
        app: '{{name}}'
        environment: prod
      annotations:
        argocd.argoproj.io/sync-wave: '{{syncWave}}'
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      source: {{ if eq .type "helm" }}
        chart: '{{chart}}'
        repoURL: '{{repoURL}}'
        targetRevision: '{{version}}'
        helm:
          valueFiles:
            - values.yaml
            - ../../overlays/prod/{{name}}/values-prod.yaml
        path: apps/system/base/{{name}}
      {{ else }}
        repoURL: https://github.com/vietcgi/infractl.git
        targetRevision: main
        path: apps/system/overlays/prod/{{name}}
        kustomize:
          buildOptions: --enable-helm
      {{ end }}
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - Validate=true
        automated:
          prune: true
          selfHeal: true
