apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: system-apps-matrix
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - clusterName: dc11a
                  env: prod
                  fqdn: argocd-dc11a.prod.emodo.io
          - list:
              elements:
                - name: argocd
                  chart: argo-cd
                  version: 8.0.10
                  repoURL: https://argoproj.github.io/argo-helm
                  namespace: argocd
                  syncWave: "-4"
                - name: cert-manager
                  chart: cert-manager
                  version: 1.13.2
                  repoURL: https://charts.jetstack.io
                  namespace: cert-manager
                  syncWave: "-3"
                - name: longhorn
                  chart: longhorn
                  version: 1.5.3
                  repoURL: https://charts.longhorn.io
                  namespace: longhorn-system
                  syncWave: "-2"
                - name: metrics-server
                  chart: metrics-server
                  version: 3.11.0
                  repoURL: https://kubernetes-sigs.github.io/metrics-server/
                  namespace: kube-system
                  syncWave: "-1"
  template:
    metadata:
      name: '{{name}}-{{clusterName}}'
      labels:
        app: '{{name}}'
        cluster: '{{clusterName}}'
        environment: '{{env}}'
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      sources:
        - chart: '{{chart}}'
          repoURL: '{{repoURL}}'
          targetRevision: '{{version}}'
        - repoURL: https://github.com/vietcgi/infra.git
          targetRevision: main
          path: apps/system/base/{{name}}
          kustomize:
            files:
              - values.yaml
              - values-{{env}}.yaml
              - values-cluster-{{clusterName}}.yaml
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      revisionHistoryLimit: 3
