apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: system-apps-matrix
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - files:
              files:
                - path: catalog/clusters.json
          - files:
              files:
                - path: catalog/apps.json
  template:
    metadata:
      name: '{{name}}-{{clusterName}}'
      labels:
        app: '{{name}}'
        cluster: '{{clusterName}}'
        environment: '{{env}}'
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'   # ← from apps.json
      sources:
        - chart: '{{chart}}'
          repoURL: '{{repoURL}}'
          targetRevision: '{{version}}'
        - repoURL: https://github.com/vietcgi/infra.git
          targetRevision: main
          path: apps/system/base/{{name}}
          helm:
            valueFiles:
              - values.yaml
              - values-{{env}}.yaml
              - values-cluster-{{clusterName}}.yaml
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      revisionHistoryLimit: 3
