apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-gitops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vietcgi/infractl.git
    targetRevision: main
    path: apps/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
