apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: system-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/vietcgi/infractl.git
        revision: main
        directories:
          - path: apps/system/overlays/prod/*
  template:
    metadata:
      name: '{{path.basename}}-system-app'
    spec:
      project: default
      source:
        repoURL: https://github.com/vietcgi/infractl.git
        targetRevision: main
        path: '{{path}}'
        kustomize:
          buildOptions: --enable-helm
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
