apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: system-apps-prod
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: cilium
          - name: coredns
          - name: prometheus
          - name: argocd
          - name: loki
          - name: grafana
          - name: nginx-ingress
          - name: cert-manager
          - name: rancher
          - name: alertmanager
          - name: sealed-secrets
          - name: metrics-server
          - name: neuvector
  template:
    metadata:
      name: '{{name}}-prod'
    spec:
      project: default
      source:
        repoURL: https://github.com/vietcgi/infractl.git
        targetRevision: main
        path: apps/system/overlays/prod/{{name}}
        kustomize:
          buildOptions: --enable-helm
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
